"""plan revisions calibration

Revision ID: 4db89d4d1929
Revises: 5a4142553199
Create Date: 2026-10-08 03:04:49.241168

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4db89d4d1929"
down_revision: str | Sequence[str] | None = "5a4142553199"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calibrations",
        sa.Column("task_type", sa.String(length=20), nullable=False),
        sa.Column("action_type", sa.String(length=20), nullable=False),
        sa.Column("coef", sa.Float(), nullable=False),
        sa.Column("samples", sa.Integer(), nullable=False),
        sa.Column("reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_calibrations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calibrations")),
    )
    op.create_index(op.f("ix_calibrations_user_id"), "calibrations", ["user_id"], unique=False)
    op.create_index(
        "uq_calibrations_user_key",
        "calibrations",
        ["user_id", "task_type", "action_type"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "plan_revisions",
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("ops", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("at_risk", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("undo", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("undone_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_plan_revisions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_revisions")),
    )
    op.create_index(op.f("ix_plan_revisions_user_id"), "plan_revisions", ["user_id"], unique=False)
    op.create_index(
        "ix_plan_revisions_user_status", "plan_revisions", ["user_id", "status"], unique=False
    )
    op.create_index(
        "uq_plan_revisions_user_proposed",
        "plan_revisions",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'proposed' AND deleted_at IS NULL"),
    )
    op.create_table(
        "study_day_limits",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_study_day_limits_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_day_limits")),
    )
    op.create_index(
        op.f("ix_study_day_limits_user_id"), "study_day_limits", ["user_id"], unique=False
    )
    op.create_index(
        "uq_study_day_limits_user_date",
        "study_day_limits",
        ["user_id", "date"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.add_column("tasks", sa.Column("deadline_buffer_days", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "deadline_buffer_days")
    op.drop_index(
        "uq_study_day_limits_user_date",
        table_name="study_day_limits",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_study_day_limits_user_id"), table_name="study_day_limits")
    op.drop_table("study_day_limits")
    op.drop_index(
        "uq_plan_revisions_user_proposed",
        table_name="plan_revisions",
        postgresql_where=sa.text("status = 'proposed' AND deleted_at IS NULL"),
    )
    op.drop_index("ix_plan_revisions_user_status", table_name="plan_revisions")
    op.drop_index(op.f("ix_plan_revisions_user_id"), table_name="plan_revisions")
    op.drop_table("plan_revisions")
    op.drop_index(
        "uq_calibrations_user_key",
        table_name="calibrations",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_calibrations_user_id"), table_name="calibrations")
    op.drop_table("calibrations")
    # ### end Alembic commands ###
