"""milestone note

Revision ID: 1209796c33d8
Revises: 654b7c7bbc1b
Create Date: 2026-10-08 17:57:50.463166

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1209796c33d8"
down_revision: str | Sequence[str] | None = "654b7c7bbc1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("milestones", sa.Column("note", sa.Text(), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("milestones", "note")
    # ### end Alembic commands ###
