"""backlog week exams

Revision ID: 654b7c7bbc1b
Revises: f2d85084c8ef
Create Date: 2026-10-08 15:38:38.366050

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "654b7c7bbc1b"
down_revision: str | Sequence[str] | None = "f2d85084c8ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exams",
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_min", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("prep_days", sa.Integer(), nullable=False),
        sa.Column("learn_min", sa.Integer(), nullable=False),
        sa.Column("review_min", sa.Integer(), nullable=False),
        sa.Column("run_min", sa.Integer(), nullable=False),
        sa.Column("plan_enabled", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_exams_subject_id_subjects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_exams_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exams")),
    )
    op.create_index(op.f("ix_exams_subject_id"), "exams", ["subject_id"], unique=False)
    op.create_index(op.f("ix_exams_user_id"), "exams", ["user_id"], unique=False)
    op.create_table(
        "exam_questions",
        sa.Column("exam_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("learned_on", sa.Date(), nullable=True),
        sa.Column("reviews_done", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
            name=op.f("fk_exam_questions_exam_id_exams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_exam_questions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_questions")),
    )
    op.create_index(op.f("ix_exam_questions_exam_id"), "exam_questions", ["exam_id"], unique=False)
    op.create_index(
        "ix_exam_questions_exam_number", "exam_questions", ["exam_id", "number"], unique=False
    )
    op.create_index(op.f("ix_exam_questions_user_id"), "exam_questions", ["user_id"], unique=False)
    op.create_table(
        "exam_sessions",
        sa.Column("exam_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("question_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
            name=op.f("fk_exam_sessions_exam_id_exams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_exam_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_sessions")),
    )
    op.create_index(op.f("ix_exam_sessions_exam_id"), "exam_sessions", ["exam_id"], unique=False)
    op.create_index(op.f("ix_exam_sessions_user_id"), "exam_sessions", ["user_id"], unique=False)
    op.create_index(
        "uq_exam_sessions_key",
        "exam_sessions",
        ["exam_id", "date", "kind"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND status <> 'missed'"),
    )
    op.add_column("backlog_items", sa.Column("planned_week", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("backlog_items", "planned_week")
    op.drop_index(
        "uq_exam_sessions_key",
        table_name="exam_sessions",
        postgresql_where=sa.text("deleted_at IS NULL AND status <> 'missed'"),
    )
    op.drop_index(op.f("ix_exam_sessions_user_id"), table_name="exam_sessions")
    op.drop_index(op.f("ix_exam_sessions_exam_id"), table_name="exam_sessions")
    op.drop_table("exam_sessions")
    op.drop_index(op.f("ix_exam_questions_user_id"), table_name="exam_questions")
    op.drop_index("ix_exam_questions_exam_number", table_name="exam_questions")
    op.drop_index(op.f("ix_exam_questions_exam_id"), table_name="exam_questions")
    op.drop_table("exam_questions")
    op.drop_index(op.f("ix_exams_user_id"), table_name="exams")
    op.drop_index(op.f("ix_exams_subject_id"), table_name="exams")
    op.drop_table("exams")
    # ### end Alembic commands ###
