"""search

Revision ID: ff87b0782059
Revises: 2b9d53be14e6
Create Date: 2026-10-06 17:50:19.172490

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ff87b0782059"
down_revision: str | Sequence[str] | None = "2b9d53be14e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notes",
        sa.Column(
            "search",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('russian', replace(lower(title), 'ё', 'е')), 'A') || "
                "setweight(to_tsvector('russian', replace(lower(body_md), 'ё', 'е')), 'B')",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.create_index("ix_notes_search", "notes", ["search"], unique=False, postgresql_using="gin")
    op.add_column(
        "sources",
        sa.Column(
            "search",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('russian', replace(lower(title), 'ё', 'е')), 'A') || "
                "setweight(to_tsvector('russian', replace(lower(author), 'ё', 'е')), 'B') || "
                "setweight(to_tsvector('russian', replace(lower(note), 'ё', 'е')), 'C')",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_sources_search", "sources", ["search"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sources_search", table_name="sources", postgresql_using="gin")
    op.drop_column("sources", "search")
    op.drop_index("ix_notes_search", table_name="notes", postgresql_using="gin")
    op.drop_column("notes", "search")
    # ### end Alembic commands ###
