"""schedule and events

Revision ID: 85430bd3ae44
Revises: 826098c89663
Create Date: 2026-10-06 12:08:57.327068

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "85430bd3ae44"
down_revision: str | Sequence[str] | None = "826098c89663"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "days_off",
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_days_off_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_days_off")),
    )
    op.create_index(op.f("ix_days_off_user_id"), "days_off", ["user_id"], unique=False)
    op.create_table(
        "semesters",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("classes_end", sa.Date(), nullable=False),
        sa.Column("session_start", sa.Date(), nullable=True),
        sa.Column("session_end", sa.Date(), nullable=True),
        sa.Column("first_week_parity", sa.String(length=8), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_semesters_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_semesters")),
    )
    op.create_index(op.f("ix_semesters_user_id"), "semesters", ["user_id"], unique=False)
    op.create_table(
        "bell_schedules",
        sa.Column("semester_id", sa.Uuid(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=True),
        sa.Column("slots", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["semester_id"],
            ["semesters.id"],
            name=op.f("fk_bell_schedules_semester_id_semesters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_bell_schedules_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bell_schedules")),
    )
    op.create_index(
        op.f("ix_bell_schedules_semester_id"), "bell_schedules", ["semester_id"], unique=False
    )
    op.create_index(op.f("ix_bell_schedules_user_id"), "bell_schedules", ["user_id"], unique=False)
    op.create_index(
        "uq_bell_schedules_semester_weekday",
        "bell_schedules",
        ["semester_id", sa.literal_column("coalesce(weekday, 0)")],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "subjects",
        sa.Column("semester_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=True),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column("control_form", sa.String(length=20), nullable=False),
        sa.Column("teachers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("synonyms", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["semester_id"],
            ["semesters.id"],
            name=op.f("fk_subjects_semester_id_semesters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_subjects_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subjects")),
    )
    op.create_index(op.f("ix_subjects_semester_id"), "subjects", ["semester_id"], unique=False)
    op.create_index(op.f("ix_subjects_user_id"), "subjects", ["user_id"], unique=False)
    op.create_table(
        "class_rules",
        sa.Column("semester_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("pair_number", sa.SmallInteger(), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("parity", sa.String(length=8), nullable=False),
        sa.Column("class_type", sa.String(length=20), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("teacher", sa.String(length=200), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["semester_id"],
            ["semesters.id"],
            name=op.f("fk_class_rules_semester_id_semesters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_class_rules_subject_id_subjects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_class_rules_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_class_rules")),
    )
    op.create_index(
        op.f("ix_class_rules_semester_id"), "class_rules", ["semester_id"], unique=False
    )
    op.create_index(op.f("ix_class_rules_subject_id"), "class_rules", ["subject_id"], unique=False)
    op.create_index(op.f("ix_class_rules_user_id"), "class_rules", ["user_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_fixed", sa.Boolean(), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("template_type", sa.String(length=20), nullable=True),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("occurrence_date", sa.Date(), nullable=True),
        sa.Column("detached", sa.Boolean(), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("class_type", sa.String(length=20), nullable=True),
        sa.Column("pair_number", sa.SmallInteger(), nullable=True),
        sa.Column("teacher", sa.String(length=200), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_events_subject_id_subjects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_events_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(op.f("ix_events_subject_id"), "events", ["subject_id"], unique=False)
    op.create_index("ix_events_template", "events", ["template_type", "template_id"], unique=False)
    op.create_index(op.f("ix_events_user_id"), "events", ["user_id"], unique=False)
    op.create_index("ix_events_user_start", "events", ["user_id", "start"], unique=False)
    op.create_index(
        "uq_events_template_occurrence",
        "events",
        ["template_type", "template_id", "occurrence_date"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND template_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_events_template_occurrence",
        table_name="events",
        postgresql_where=sa.text("deleted_at IS NULL AND template_id IS NOT NULL"),
    )
    op.drop_index("ix_events_user_start", table_name="events")
    op.drop_index(op.f("ix_events_user_id"), table_name="events")
    op.drop_index("ix_events_template", table_name="events")
    op.drop_index(op.f("ix_events_subject_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_class_rules_user_id"), table_name="class_rules")
    op.drop_index(op.f("ix_class_rules_subject_id"), table_name="class_rules")
    op.drop_index(op.f("ix_class_rules_semester_id"), table_name="class_rules")
    op.drop_table("class_rules")
    op.drop_index(op.f("ix_subjects_user_id"), table_name="subjects")
    op.drop_index(op.f("ix_subjects_semester_id"), table_name="subjects")
    op.drop_table("subjects")
    op.drop_index(
        "uq_bell_schedules_semester_weekday",
        table_name="bell_schedules",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_bell_schedules_user_id"), table_name="bell_schedules")
    op.drop_index(op.f("ix_bell_schedules_semester_id"), table_name="bell_schedules")
    op.drop_table("bell_schedules")
    op.drop_index(op.f("ix_semesters_user_id"), table_name="semesters")
    op.drop_table("semesters")
    op.drop_index(op.f("ix_days_off_user_id"), table_name="days_off")
    op.drop_table("days_off")
    # ### end Alembic commands ###
