"""projects and milestones

Revision ID: 41618aa3f8eb
Revises: 2615069c4573
Create Date: 2026-10-06 15:49:54.985798

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "41618aa3f8eb"
down_revision: str | Sequence[str] | None = "2615069c4573"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("contacts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("weekly_norm_min", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("is_work_default", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_projects_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_projects_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(op.f("ix_projects_user_id"), "projects", ["user_id"], unique=False)
    op.create_index(
        "uq_projects_user_work_default",
        "projects",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND is_work_default"),
    )
    op.create_table(
        "milestones",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_milestones_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_milestones_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_milestones")),
    )
    op.create_index(op.f("ix_milestones_project_id"), "milestones", ["project_id"], unique=False)
    op.create_index(op.f("ix_milestones_user_id"), "milestones", ["user_id"], unique=False)
    op.add_column("subtasks", sa.Column("occurrence_date", sa.Date(), nullable=True))
    op.create_index(
        "uq_subtasks_task_occurrence",
        "subtasks",
        ["task_id", "occurrence_date"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND occurrence_date IS NOT NULL"),
    )
    op.add_column("tasks", sa.Column("project_id", sa.Uuid(), nullable=True))
    op.add_column("tasks", sa.Column("milestone_id", sa.Uuid(), nullable=True))
    op.add_column("tasks", sa.Column("recurrence", sa.String(length=500), nullable=True))
    op.add_column("tasks", sa.Column("recurrence_start", sa.Date(), nullable=True))
    op.create_index(op.f("ix_tasks_project_id"), "tasks", ["project_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_tasks_project_id_projects"),
        "tasks",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_tasks_milestone_id_milestones"),
        "tasks",
        "milestones",
        ["milestone_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_tasks_milestone_id_milestones"), "tasks", type_="foreignkey")
    op.drop_constraint(op.f("fk_tasks_project_id_projects"), "tasks", type_="foreignkey")
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_column("tasks", "recurrence_start")
    op.drop_column("tasks", "recurrence")
    op.drop_column("tasks", "milestone_id")
    op.drop_column("tasks", "project_id")
    op.drop_index(
        "uq_subtasks_task_occurrence",
        table_name="subtasks",
        postgresql_where=sa.text("deleted_at IS NULL AND occurrence_date IS NOT NULL"),
    )
    op.drop_column("subtasks", "occurrence_date")
    op.drop_index(op.f("ix_milestones_user_id"), table_name="milestones")
    op.drop_index(op.f("ix_milestones_project_id"), table_name="milestones")
    op.drop_table("milestones")
    op.drop_index(
        "uq_projects_user_work_default",
        table_name="projects",
        postgresql_where=sa.text("deleted_at IS NULL AND is_work_default"),
    )
    op.drop_index(op.f("ix_projects_user_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
