"""telegram link

Revision ID: 826098c89663
Revises: 7be9f4977c40
Create Date: 2026-10-06 01:55:17.582415

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "826098c89663"
down_revision: str | Sequence[str] | None = "7be9f4977c40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_link_codes",
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_telegram_link_codes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_link_codes")),
        sa.UniqueConstraint("code_hash", name=op.f("uq_telegram_link_codes_code_hash")),
    )
    op.create_index(
        op.f("ix_telegram_link_codes_user_id"), "telegram_link_codes", ["user_id"], unique=False
    )
    op.add_column("users", sa.Column("tg_user_id", sa.BigInteger(), nullable=True))
    op.create_unique_constraint(op.f("uq_users_tg_user_id"), "users", ["tg_user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_tg_user_id"), "users", type_="unique")
    op.drop_column("users", "tg_user_id")
    op.drop_index(op.f("ix_telegram_link_codes_user_id"), table_name="telegram_link_codes")
    op.drop_table("telegram_link_codes")
    # ### end Alembic commands ###
