export const queryKeys = {
  health: ['health'] as const,
  me: ['me'] as const,
  settings: ['me', 'settings'] as const,
  telegram: ['me', 'telegram'] as const,
  semesters: ['semesters'] as const,
  bells: (semesterId: string) => ['semesters', semesterId, 'bells'] as const,
  daysOff: ['days-off'] as const,
  subjects: ['subjects'] as const,
  classRules: (semesterId: string) => ['class-rules', semesterId] as const,
  classRulesAll: ['class-rules'] as const,
  recurring: ['recurring-events'] as const,
  calendarAll: ['calendar'] as const,
  calendar: (from: string, to: string) => ['calendar', from, to] as const,
  categories: ['categories'] as const,
  actionTypes: ['action-types'] as const,
  tasks: ['tasks'] as const,
  taskList: (params: object) => ['tasks', 'list', params] as const,
  task: (id: string) => ['tasks', 'detail', id] as const,
  backlogAll: ['backlog'] as const,
  backlog: (status: string) => ['backlog', status] as const,
}
