export const queryKeys = {
  health: ['health'] as const,
  me: ['me'] as const,
  settings: ['me', 'settings'] as const,
  telegram: ['me', 'telegram'] as const,
  push: ['me', 'push'] as const,
  pushBrowser: ['push-browser'] as const,
  reminders: ['me', 'reminders'] as const,
  semesters: ['semesters'] as const,
  bells: (semesterId: string) => ['semesters', semesterId, 'bells'] as const,
  daysOff: ['days-off'] as const,
  subjects: ['subjects'] as const,
  classRules: (semesterId: string) => ['class-rules', semesterId] as const,
  classRulesAll: ['class-rules'] as const,
  recurring: ['recurring-events'] as const,
  calendarAll: ['calendar'] as const,
  calendar: (from: string, to: string) => ['calendar', from, to] as const,
  categories: ['categories'] as const,
  actionTypes: ['action-types'] as const,
  tasks: ['tasks'] as const,
  taskList: (params: object) => ['tasks', 'list', params] as const,
  task: (id: string) => ['tasks', 'detail', id] as const,
  backlogAll: ['backlog'] as const,
  backlog: (status: string) => ['backlog', status] as const,
  quickParse: (text: string) => ['quick-parse', text] as const,
  attachments: (ownerType: string, ownerId: string) => ['attachments', ownerType, ownerId] as const,
  projects: ['projects'] as const,
  project: (id: string) => ['projects', 'detail', id] as const,
  notesAll: ['notes'] as const,
  notesList: ['notes', 'list'] as const,
  noteList: (params: object) => ['notes', 'list', params] as const,
  note: (id: string) => ['notes', 'detail', id] as const,
  search: (q: string, subjectId?: string) => ['search', q, subjectId ?? ''] as const,
  sourcesAll: ['sources'] as const,
  sources: (subjectId: string) => ['sources', subjectId] as const,
  plan: ['plan'] as const,
  dayLimits: ['plan', 'day-limits'] as const,
  calibration: ['calibration'] as const,
  job: (id: string) => ['jobs', id] as const,
  latestBreakdown: (taskId: string) => ['tasks', 'breakdown', taskId] as const,
  breakdownTemplates: ['breakdown-templates'] as const,
}
